packages:
  - packages/services/demo/*
  - packages/services/*
  - packages/migrations
  - packages/services/external-composition/*
  - packages/web/*
  - packages/libraries/*
  - integration-tests
  - deployment
  - scripts
  - rules
